### ISSUE TITLE
Script doesn't work on Windows.

### ISSUE THREAD

**Issue by masterofobzene** [Ajatt-Tools/videoclip#25] opened 2023-12-06 20:38 UTC
Paths are not being recognized by the script.
All I get is "E:\profile\Downloads" "Error: couldn't create the clip. Does E:\profile\Downloads exist?"

* The folder exists and the path is correct
* Using "" \\\ \\   /  or //    doesn't make any difference.
* Changing the path by "hardcoding" it in the script (bypassing config file) does the same.

**Comment by tatsumoto-ren** [comment] 2023-12-06 22:05
> Do you think there is any other way to join paths in a "agnostic" way? (not adding / or \ automatically)

Avoid joining paths by hand and use mpv's built-in functions for that (join_path).

**Comment by tatsumoto-ren** [comment] 2023-12-07 20:29
> there is nobody to fix it

So are you not going to fix the issue? If so, I'll delete it.

At least config saving should work now, but you need to test it.

**Comment by tatsumoto-ren** [comment] 2023-12-07 22:53
I'd rather wait for someone to volunteer to fix it since we've already made a lot of work to support mac and windows, and it would be a waste to abandon it.

**Comment by tatsumoto-ren** [comment] 2023-12-08 01:44
> where it joins the variables path+filename; "E:\profile\Downloads/clip.mp4"
> If I hardcode the path ending with \ I will get "E:\profile\Downloads\/clip.mp4"

Is this the input path or the output path?

**Comment by tatsumoto-ren** [comment] 2023-12-08 21:23
> Its the output path. Does this script need an input path for something? I thought the input is just the playing video.

You didn't say what part of the source code you changed so it wasn't clear. The input file is set automatically by mpv and should be correct. The output path is constructed by the user-script. 

> Maybe a temporal "Windows script temporarily not working" or something like that?

You need to rule out the possibility that the problem is on your side. Probably you don't have `mpv` in your `PATH` and you need to add it. GNU users don't have to do so because installed programs are added to the `PATH` automatically, but Windows is different.

**Comment by tatsumoto-ren** [comment] 2023-12-09 16:01
Alright, can I close this issue as resolved?

**Closed** 2023-12-10 03:05 UTC
